// ModMed Constants extracted from source project
// You may need to adapt these for your project structure

/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedAuthenticationBaseUrl = process.env.MODMED_AUTH_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedAuthenticationData = process.env.MODMED_AUTH_DATA || ""; 
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedFhirBaseUrl = process.env.MODMED_FHIR_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedFirmPrefix = process.env.MODMED_FIRM_PREFIX || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedId = process.env.MODMED_ID || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedPassword = process.env.MODMED_PASSWORD || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedKey = process.env.MODMED_KEY || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedFullAuthURL = modmedAuthenticationBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts:export const modmedFullFhirURL = modmedFhirBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/core/constants.ts-export const CHANGE_PASSWORD_ATTRS = [
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedAuthenticationBaseUrl = process.env.MODMED_AUTH_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedAuthenticationData = process.env.MODMED_AUTH_DATA || ""; 
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedFhirBaseUrl = process.env.MODMED_FHIR_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedFirmPrefix = process.env.MODMED_FIRM_PREFIX || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedId = process.env.MODMED_ID || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedPassword = process.env.MODMED_PASSWORD || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedKey = process.env.MODMED_KEY || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedFullAuthURL = modmedAuthenticationBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts:export const modmedFullFhirURL = modmedFhirBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/populate/core/constants.ts-export const CHANGE_PASSWORD_ATTRS = [
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedAuthenticationBaseUrl = process.env.MODMED_AUTH_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedAuthenticationData = process.env.MODMED_AUTH_DATA || ""; 
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedFhirBaseUrl = process.env.MODMED_FHIR_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedFirmPrefix = process.env.MODMED_FIRM_PREFIX || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedId = process.env.MODMED_ID || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedPassword = process.env.MODMED_PASSWORD || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedKey = process.env.MODMED_KEY || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedFullAuthURL = modmedAuthenticationBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts:export const modmedFullFhirURL = modmedFhirBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/doctors/src/core/constants.ts-export const CHANGE_PASSWORD_ATTRS = [
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedAuthenticationBaseUrl = process.env.MODMED_AUTH_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedAuthenticationData = process.env.MODMED_AUTH_DATA || ""; 
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedFhirBaseUrl = process.env.MODMED_FHIR_BASE_URL || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedFirmPrefix = process.env.MODMED_FIRM_PREFIX || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedId = process.env.MODMED_ID || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedPassword = process.env.MODMED_PASSWORD || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedKey = process.env.MODMED_KEY || "";
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedFullAuthURL = modmedAuthenticationBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts:export const modmedFullFhirURL = modmedFhirBaseUrl.replace('{firm_url_prefix}', modmedFirmPrefix);
/Users/sarfraz/PPX/development/web/provenmedical-durin_api-70f98539257e/api/src/core/constants.ts-export const CHANGE_PASSWORD_ATTRS = [
